variable "ami" {
  type        = string
  description = "Confluent Platform image ID generated by Packer builds"
}

variable "zk_instance_type" {
  type        = string
  description = "Instance type (e.g. t2.micro, t2.small, etc)"
  default     = "t2.small"
}

variable "broker_instance_type" {
  type        = string
  description = "Instance type (e.g. t2.micro, t2.small, etc)"
  default     = "t2.medium"
}

variable "user" {
  type        = string
  description = "User name"
}

variable "owner" {
  type = string
  description = "Owner name"
  default = "Ismail Mayat"
}

variable "owner_email" {
  type = string
  description = "Owner name"
  default ="imayat@confluent.io"
}

variable "key_name" {
  type        = string
  description = "Key pair name"
}

provider "aws" {
  profile = "default"
  region  = "eu-west-1"
}

resource "aws_instance" "zk" {
  count = 1

  ami           = var.ami
  instance_type = var.zk_instance_type
  tags = {
    Name = "${var.user}-zk${count.index}"
    Owner = "${var.owner}"
    Owner_Email ="${var.owner_email}"

  }
  key_name = var.key_name
}

resource "aws_instance" "broker" {
  count         = 3
  ami           = var.ami
  instance_type = var.broker_instance_type
  tags = {
    Name = "${var.user}-broker${count.index}"
    Owner = "${var.owner}"
    Owner_Email ="${var.owner_email}"
  }
  key_name = var.key_name
}

resource "aws_instance" "c3" {
  ami           = var.ami
  instance_type = var.broker_instance_type
  tags = {
    Name = "${var.user}-c3"
    Owner = "${var.owner}"
    Owner_Email ="${var.owner_email}"
  }
  key_name = var.key_name
}

output "zk_ips" {
  value = ["${aws_instance.zk.*.private_ip}"]
}
output "zk_dns" {
  value = ["${aws_instance.zk.*.public_dns}"]
}

output "broker_ips" {
  value = ["${aws_instance.broker.*.private_ip}"]
}
output "broker_dns" {
  value = ["${aws_instance.broker.*.public_dns}"]
}

output "c3_ips" {
  value = ["${aws_instance.c3.*.private_ip}"]
}
output "c3_dns" {
  value = ["${aws_instance.c3.*.public_dns}"]
}